services:
  nginx:
    build:
      context: docker
      dockerfile: nginx.docker
    restart: always
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - hackaton-network
  pgsql:
    build:
      context: docker
      dockerfile: pgsql.docker
    restart: always
    environment:
    networks:
      - hackaton-network
networks:
  hackaton-network:
    driver: bridge
